errata:
  url: "https://errata.devel.redhat.com/api/v1/erratum/"
  kerberos-conf: "/etc/krb5.conf"
  username: "<your Kerberos username>"
  realm: "<Kerberos Realm>"
jira:
  url: "https://issues.redhat.com"
  token: "<your Jira Access Token>"
  params:
    jql: "<jql issues search query>"
