errata:
  url: "https://errata.devel.redhat.com/api/v1/erratum/"
  kerberos-conf: "/etc/krb5.conf"
  username: "<your Kerberos username>"
  realm: "<Kerberos Realm>"
jira:
  url: "https://issues.redhat.com"
  token: "<your Jira Access Token>"
  params:
    jql: "<jql issues search query>" 
    #Example jql for all IO OCPBUGS closed in 4.12: 
    #project = "OCPBUGS" AND component="Insights Operator" AND status = Closed AND affectedversion = 4.12
